---
- name: "Package name is defined?"
  ansible.builtin.fail:
    msg: "Name (_name var) not defined for {{ _item }}"
  when: _name is not defined

- name: "Check whether installed: {{ _name }}"
  shell: "{{ version_command }}"
  register: need_install
  ignore_errors: true
  changed_when: false

  environment:
    PATH: "{{ install_directory }}:{{ ansible_env.PATH }}"
  tags:
    - skip_ansible_lint

- name: "Install package when needed: {{ _name }}"
  when: need_install.rc != 0 or
      ( need_install.rc == 0 and version not in need_install.stdout )
  block:
    - name: Generate temporary filename
      ansible.builtin.tempfile:
        state: file
      register: tempfile

    - name: "Download: {{ _name }}"
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ tempfile.path }}"
        mode: '0600'
        force: true

    - name: "Install {{ _name }}"
      ansible.builtin.shell: >-
        set -eo pipefail &&
        {{ install_command | replace('%downloaded%', tempfile.path) }}
      changed_when: false
      args:
        executable: /bin/bash

    - name: Delete temporary data
      ansible.builtin.file:
        path: "{{ tempfile.path }}"
        state: absent

    - name: "Check installed: {{ _name }}"
      ansible.builtin.command: "{{ version_command }}"
      register: just_installed
      failed_when: just_installed.rc != 0 or
          ( just_installed.rc == 0 and version not in just_installed.stdout )
      changed_when: false
      environment:
        PATH: "{{ install_directory }}:{{ ansible_env.PATH }}"
