---
-
  name: Change user shell
  become: true
  user:
    shell: /bin/zsh
    name: "{{ ansible_user }}"
-
  name: Create antigen directory
  file:
    path: "{{ workstation_antigen_directory }}"
    state: directory
    mode: "0755"
-
  name: Download antigen
  ansible.builtin.get_url:
    url: "{{ workstation_antigen_url }}"
    dest: "{{ workstation_antigen_directory }}/antigen.zsh"
  register: uri_output
  until: uri_output.status_code == 200
  retries: 5
  delay: 2
-
  name: Create dotfiles directory
  file:
    path: "{{ workstation_dotfiles_directory }}"
    state: directory
    mode: "0755"
-
  name: Download dotfiles
  git:
    repo: "{{ workstation_dotfiles_repository }}"
    dest: "{{ workstation_dotfiles_directory }}"
    version: "{{ workstation_dotfiles_version | d('master') }}"
-
  name: Install dotfiles
  changed_when: false
  command: "{{ workstation_dotfiles_install_script }}"
-
  name: Download dotfiles fonts
  block:
    - name: Create local fonts directory
      file:
        path: "{{ workstation_dotfiles_fonts_directory }}"
        state: directory
        mode: "0755"
    - name: Install required fonts
      get_url:
        url: "{{ item }}"
        dest: "{{ workstation_dotfiles_fonts_directory }}/{{ item | basename }}"
      loop: "{{ workstation_dotfiles_fonts }}"
-
  name: "Set direnv configuration directory"
  set_fact:
    direnv_config_dir: "{{ ansible_user_dir }}/.config/direnv/lib"

-
  name: "Create direnv configuration directory"
  file:
    path: "{{ direnv_config_dir }}"
    state: directory
    mode: "0755"
-
  name: "Setup direnv use_terraform"
  ansible.builtin.copy:
    dest: "{{ direnv_config_dir }}/use_terraform.sh"
    content: |
      ### Generated by ansible ###
      use_terraform() {
        DIR="$(expand_path .)/.mw-bin"
        PATH_add "$DIR"
        mkdir -p "$DIR"
        if type -p tfswitch > /dev/null ; then
          tfswitch -b "$DIR/terraform"
        else
          echo
          echo "tfswitch is required!" >&2
          echo
        fi
      }
