---
- name: Check if krew is installed
  ansible.builtin.command: krew version
  register: krew_check
  changed_when: false
  ignore_errors: yes
  environment:
    PATH: "{{ workstation_asdf_dest }}/bin:{{ workstation_asdf_dest }}/shims:{{ workstation_tools_install_directory }}:{{ ansible_env.PATH }}"
-
  name: Do install and upgrade krew plugins when installed
  when: krew_check.rc == 0
  block:
    -
      name: Install krew plugins
      ansible.builtin.command: "krew install {{ item }}"
      register: krew_install
      changed_when: krew_install.rc == 0 and 'installed' in krew_install.stdout
      loop: "{{ workstation_krew_plugins }}"
      environment:
        PATH: "{{ workstation_asdf_dest }}/bin:{{ workstation_asdf_dest }}/shims:{{ workstation_tools_install_directory }}:{{ ansible_env.PATH }}"
    -
      name: Upgrade krew plugins
      ansible.builtin.command: "krew upgrade"
      changed_when: false
      environment:
        PATH: "{{ workstation_asdf_dest }}/bin:{{ workstation_asdf_dest }}/shims:{{ workstation_tools_install_directory }}:{{ ansible_env.PATH }}"
