---
-
  name: Configure proxy
  import_tasks: proxy_configure.yml
  tags: proxy_configure
-
  name: Install system packages
  import_tasks: system_packages.yml
  tags: system_packages
-
  name: Install docker
  import_role:
    name: geerlingguy.docker
  become: true
  vars:
    docker_users: "{{ workstation_docker_users }}"
    docker_install_compose: "{{ workstation_docker_install_compose }}"
    docker_compose_version: "{{ workstation_docker_compose_version }}"
    docker_install_compose_plugin: "{{ workstation_docker_install_compose_plugin }}"
  when: workstation_docker_enabled and ansible_os_family | lower != "archlinux"
  tags:
    - docker
-
  name: Install tools
  import_tasks: tools.yml
  tags: tools
-
  name: Install dotfiles
  import_tasks: dotfiles.yml
  when: workstation_dotfiles_enabled
  tags: dotfiles
