---
- name: Update apt packages
  become: true
  block:
    -
      name: Install essential packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - python3-pip
          - python3-apt
          - dirmngr
          - gpg
        state: present
    -
      name: Add Apt keys
      ansible.builtin.apt_key:
        url: "{{ item.url }}"
        id: "{{ item.id }}"
        state: present
      loop: "{{ workstation_apt_keys }}"
    -
      name: Update apt-get repo and cache
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    -
      name: Add repositories
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        codename: "{{ item.codename | d() }}"
      loop: "{{ workstation_repositories }}"
