---
-
  name: Include release specific variables
  include_vars: "{{ _loop_var }}"
  loop: "{{ query('first_found', _params) }}"
  loop_control:
    loop_var: _loop_var
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
      skip: true
-
  name: Prepare system to install
  include_tasks:
    file: "{{ system_package_file }}"
  with_first_found:
    - files:
        - system_packages_{{ ansible_os_family | lower }}.yml
      skip: True
  loop_control:
    loop_var: system_package_file
-
  name: Install common packages using standard package manager
  package:
    name: "{{ workstation_packages }}"
    state: present
  register: package_res
  until: package_res is success
  become: true
  retries: 3
  delay: 10
-
  name: Setup configured locale
  locale_gen:
    name: "{{ item }}"
    state: present
  become: true
  tags:
    - locales
  with_items: "{{ workstation_locales }}"
