---
-
  name: Include release specific variables
  ansible.builtin.include_vars: "{{ _loop_var }}"
  loop: "{{ query('first_found', _params) }}"
  loop_control:
    loop_var: _loop_var
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
      skip: true
-
  name: Prepare system to install
  ansible.builtin.include_tasks:
    file: "{{ system_package_file }}"
  with_first_found:
    - files:
        - system_packages_{{ ansible_os_family | lower }}.yml
      skip: True
  loop_control:
    loop_var: system_package_file
-
  name: Install common packages using standard package manager
  ansible.builtin.package:
    name: "{{ workstation_packages }}"
    state: present
  register: package_res
  until: package_res is success
  become: true
  retries: 3
  delay: 10
-
  name: Install Vagrant and Swaks using yay
  when: ansible_os_family | lower == "archlinux"
  block:
    - name: Check if yay is already installed
      ansible.builtin.command: yay --version
      register: yay_check
      changed_when: false
      ignore_errors: true
    -
      name: Install yay
      when: yay_check.rc != 0
      block:
        - 
          name: Clone yay repository
          ansible.builtin.git:
            repo: "https://aur.archlinux.org/yay.git"
            dest: /tmp/yay
        -
          name: Compile yay
          ansible.builtin.shell: |
            cd /tmp/yay
            makepkg -si --noconfirm
          changed_when: false
    -
      name: Install Vagrant and Swaks
      ansible.builtin.shell: |
        export PATH=/usr/bin/core_perl:$PATH
        yay -S --noconfirm vagrant swaks
      changed_when: false

-
  name: Setup configured locale
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  become: true
  tags:
    - locales
  with_items: "{{ workstation_locales }}"
