---
dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
driver:
  name: docker
platforms:
  - name: arch
    image: 'archlinux:base'
    groups:
      - complete
  - name: ubuntu-2204
    image: 'ubuntu:22.04'
    groups:
      - system_packages
  - name: debian-11
    image: 'debian:11'
    groups:
      - complete
lint: |
  set -ex
  yamllint .
  ansible-lint .
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
    host_vars:
      arch:
        workstation_locales: []
verifier:
  name: ansible
