---
dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
driver:
  name: docker
platforms:
  - name: arch
    image: 'archlinux:base'
    groups:
      - complete
#  - name: ubuntu-2404
#    image: 'ubuntu:24.04'
#    groups:
#      - system_packages
  - name: debian-12
    image: 'debian:12'
    groups:
      - complete
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
        workstation_asdf_tools:
          direnv: [ latest ]
          helm: [ latest ]
          kubectl: [ latest ]
          krew: [ latest ]
    host_vars:
      arch:
        workstation_locales: []
verifier:
  name: ansible
